[project]
name = "vesuvius_np"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "vesuvius>=0.1.10",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
